// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialAddAudiTable_PostCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialAddAudiTable_PostCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191324194_InitialAddAudiTable_PostCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
